name: "Test"

on:
  push:
    paths:
      - "**.go"
      - ".github/workflows/*.yml"

jobs:
  ping:
    strategy:
      matrix:
        test:
          - server:
              url: "https://files.betacraft.uk/server-archive/release/1.0/1.0.1.jar"
              version: "101"
              type: "vanilla"
            test:
              pattern: "Beta18"
              delay: 20
              timeout: 120
          - server:
              url: "https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.0.0-SNAPSHOT.jar"
              version: "101"
              type: "craftbukkit"
            test:
              pattern: "Beta18"
              delay: 20
              timeout: 120
          - server:
              url: "https://piston-data.mojang.com/v1/objects/5be700523a729bb78ef99206fb480a63dcd09825/server.jar"
              version: "142"
              type: "vanilla"
            test:
              pattern: "14"
              delay: 20
              timeout: 120
          - server:
              url: "https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.4.7-R1.1-SNAPSHOT.jar"
              version: "147"
              type: "craftbukkit"
            test:
              pattern: "14"
              delay: 20
              timeout: 120
          - server:
              url: "https://cdn.getbukkit.org/spigot/spigot-1.4.7-R1.1-SNAPSHOT.jar"
              version: "147"
              type: "spigot"
            test:
              pattern: "14"
              delay: 20
              timeout: 120
          - server:
              url: "https://piston-data.mojang.com/v1/objects/0252918a5f9d47e3c6eb1dfec02134d1374a89b4/server.jar"
              version: "161"
              type: "vanilla"
            test:
              pattern: "16"
              delay: 20
              timeout: 120
          - server:
              url: "https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.6.1-R0.1-SNAPSHOT.jar"
              version: "161"
              type: "craftbukkit"
            test:
              pattern: "16"
              delay: 20
              timeout: 120
          - server:
              url: "https://cdn.getbukkit.org/spigot/spigot-1.6.2-R1.1-SNAPSHOT.jar"
              version: "162"
              type: "spigot"
            test:
              pattern: "16"
              delay: 20
              timeout: 120
          - server:
              url: "https://piston-data.mojang.com/v1/objects/3716cac82982e7c2eb09f83028b555e9ea606002/server.jar"
              version: "172"
              type: "vanilla"
            test:
              pattern: "16"
              delay: 20
              timeout: 120
          - server:
              url: "https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.7.2-R0.4-20140216.012104-3.jar"
              version: "172"
              type: "craftbukkit"
            test:
              pattern: "17"
              delay: 20
              timeout: 120
          - server:
              url: "https://cdn.getbukkit.org/spigot/spigot-1.7.2-R0.4-SNAPSHOT-1339.jar"
              version: "172"
              type: "spigot"
            test:
              pattern: "17"
              delay: 20
              timeout: 120

    name: "TestPing${{ matrix.test.test.pattern }} (${{ matrix.test.server.type }} ${{ matrix.test.server.version }})"
    runs-on: "ubuntu-latest"

    env:
      HOST: "127.0.0.1"
      PORT: "25565"
      JVM_ARGS: "-Xmx512M"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Setup Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: "^1.13"
      - name: "Setup Java"
        uses: "actions/setup-java@v3"
        with:
          distribution: "adopt-hotspot"
          java-version: "8"
      - name: "Pull Minecraft server cache"
        id: "mc-server-cache"
        uses: "actions/cache@v3"
        with:
          path: "server_${{ matrix.test.server.version }}"
          key: "mc-server-${{ matrix.test.server.type }}-v${{ matrix.test.server.version }}-cache"
      - name: "Download Minecraft server"
        if: "!steps.mc-server-cache.outputs.cache-hit"
        run: |
          mkdir -p server_${{ matrix.test.server.version }}/${{ matrix.test.server.type }}
          curl --fail ${{ matrix.test.server.url }} -o server_${{ matrix.test.server.version }}/${{ matrix.test.server.type }}/server.jar
      - name: "Run test server and run test"
        uses: "nick-fields/retry@v2"
        env:
          TYPE: "${{ matrix.test.server.type }}"
        with:
          timeout_seconds: ${{ matrix.test.test.timeout }}
          max_attempts: 5
          retry_on: error
          command: |
            cd server_${{ matrix.test.server.version }}/${{ matrix.test.server.type }}
            java ${{ env.JVM_ARGS }} -jar server.jar | sed 's/>//g' &
            trap "killall -9 java" EXIT
            cd ../..
            sleep ${{ matrix.test.test.delay }}
            go test github.com/alteamc/minequery/v2 -run ${{ matrix.test.test.pattern }}
          on_retry_command: rm -rf server_${{ matrix.test.server.version }}/${{ matrix.test.server.type }}/world*