name: "Test"

on:
  push:
    paths:
      - "**.go"
      - ".github/workflows/*.yml"

jobs:
  check_101:
    name: "Test Minecraft 1.0.1 pinging"
    runs-on: "ubuntu-latest"

    env:
      HOST: "127.0.0.1"
      PORT: "25565"

    step:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Pull Minecraft server cache"
        id: "mc-server-v101-cache"
        uses: "actions/cache@v3"
        with:
          path: "server_101"
          key: "mc-server-cache"

      - name: "Download Minecraft server"
        if: "!steps.mc-server-cache.outputs.cache-hit"
        run: |
          mkdir server_101
          curl https://files.betacraft.uk/server-archive/release/1.0/1.0.1.jar > server_101/server.jar

      - name: "Run test server and run tests"
        run: |
          cd server_101
          java -Xmx512M -jar server.jar &
          cd ..
          sleep 10
          go test github.com/alteamc/minequery/v2 -run TestPingBeta18
          killall -9 java

  check_142:
    name: "Test Minecraft 1.4.2 pinging"
    runs-on: "ubuntu-latest"

    env:
      HOST: "127.0.0.1"
      PORT: "25565"

    step:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Pull Minecraft server cache"
        id: "mc-server-v142-cache"
        uses: "actions/cache@v3"
        with:
          path: "server_142"
          key: "mc-server-cache"

      - name: "Download Minecraft server"
        if: "!steps.mc-server-cache.outputs.cache-hit"
        run: |
          mkdir server_142
          curl https://piston-data.mojang.com/v1/objects/5be700523a729bb78ef99206fb480a63dcd09825/server.jar > server_142/server.jar

      - name: "Run test server and run tests"
        run: |
          cd server_142
          java -Xmx512M -jar server.jar &
          cd ..
          sleep 10
          go test github.com/alteamc/minequery/v2 -run TestPing14
          killall -9 java

  check_161:
    name: "Test Minecraft 1.6.1 pinging"
    runs-on: "ubuntu-latest"

    env:
      HOST: "127.0.0.1"
      PORT: "25565"

    step:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Pull Minecraft server cache"
        id: "mc-server-v161-cache"
        uses: "actions/cache@v3"
        with:
          path: "server_161"
          key: "mc-server-cache"

      - name: "Download Minecraft server"
        if: "!steps.mc-server-cache.outputs.cache-hit"
        run: |
          mkdir server_161
          curl https://piston-data.mojang.com/v1/objects/0252918a5f9d47e3c6eb1dfec02134d1374a89b4/server.jar > server_161/server.jar

      - name: "Run test server and run tests"
        run: |
          cd server_161
          java -Xmx512M -jar server.jar &
          cd ..
          sleep 10
          go test github.com/alteamc/minequery/v2 -run TestPing16
          killall -9 java

  check_172:
    name: "Test Minecraft 1.7.2 pinging"
    runs-on: "ubuntu-latest"

    env:
      HOST: "127.0.0.1"
      PORT: "25565"

    step:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Pull Minecraft server cache"
        id: "mc-server-v172-cache"
        uses: "actions/cache@v3"
        with:
          path: "server_172"
          key: "mc-server-cache"

      - name: "Download Minecraft server"
        if: "!steps.mc-server-cache.outputs.cache-hit"
        run: |
          mkdir server_172
          curl https://piston-data.mojang.com/v1/objects/3716cac82982e7c2eb09f83028b555e9ea606002/server.jar > server_172/server.jar

      - name: "Run test server and run tests"
        run: |
          cd server_172
          java -Xmx512M -jar server.jar &
          cd ..
          sleep 10
          go test github.com/alteamc/minequery/v2 -run TestPing17
          killall -9 java